name: AndrewFarage
favicon: null
layout_spectrum: 0.052006413228809834
typography_spectrum: 0.33583684265613556
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.648674217518419
  lightness: 0.1744311833754182
  saturation: 0.4163261903449893
  rhythmicContrast: 0.4786244442220777
purpose: []
